<?xml version="1.0" encoding="UTF-8"?>
<testng-results total="3" passed="1" failed="1" skipped="1">
  <suite name="SampleTestSuite" duration-ms="2500" started-at="2023-08-13T12:00:00Z" finished-at="2023-08-13T12:00:02Z">
    <test name="SampleTest" duration-ms="2500" started-at="2023-08-13T12:00:00Z" finished-at="2023-08-13T12:00:02Z">
      <class name="com.example.SampleTest">
        <test-method name="testSuccess" status="PASS" duration-ms="500" started-at="2023-08-13T12:00:00Z" finished-at="2023-08-13T12:00:00Z" is-config="false">
        </test-method>
        <test-method name="testFailure" status="FAIL" duration-ms="1000" started-at="2023-08-13T12:00:01Z" finished-at="2023-08-13T12:00:02Z" is-config="false">
          <exception class="java.lang.AssertionError" message="Test failed">
            <full-stacktrace>java.lang.AssertionError: Test failed
        at com.example.SampleTest.testFailure(SampleTest.java:42)</full-stacktrace>
          </exception>
        </test-method>
        <test-method name="testSkipped" status="SKIP" duration-ms="0" started-at="2023-08-13T12:00:02Z" finished-at="2023-08-13T12:00:02Z" is-config="false">
        </test-method>
      </class>
    </test>
  </suite>
</testng-results>